export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_OK = "AGREGAR_PRODUCTO_OK";
export const AGREGAR_PRODUCTO_ERR = "AGREGAR_PRODUCTO_ERR";

export const OBTENER_PRODUCTO_CARGANDO = "OBTENER_PRODUCTO_CARGANDO";
export const OBTENER_PRODUCTO_OK = "OBTENER_PRODUCTO_OK";
export const OBTENER_PRODUCTO_ERR = "OBTENER_PRODUCTO_ERR";

export const SELECCIONAR_PRODUCTO = "SELECCIONAR_PRODUCTO";
export const ELIMINAR_PRODUCTO_OK = "ELIMINAR_PRODUCTO_OK";
export const ELIMINAR_PRODUCTO_ERR = "ELIMINAR_PRODUCTO_ERR";
export const EDITAR_PRODUCTO_OK = "EDITAR_PRODUCTO_OK";
export const EDITAR_PRODUCTO_ERR = "EDITAR_PRODUCTO_ERR";
