export const AGREGAR_PRODUCTO = 'AGREGAR_PRODUCTO'
export const AGREGAR_PRODUCTO_OK = 'AGREGAR_PRODUCTO_OK'
export const AGREGAR_PRODUCTO_ERR = 'AGREGAR_PRODUCTO_ERR'

export const OBTENER_PRODUCTO = 'OBTENER_PRODUCTO'
export const OBTENER_PRODUCTO_OK = 'OBTENER_PRODUCTO_OK'
export const OBTENER_PRODUCTO_ERR = 'OBTENER_PRODUCTO_ERR'

